//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVersionBootstrap4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class establecimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public establecimientos()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.favoritos = new HashSet<favoritos>();
        }
    
        public int Id_establecimiento { get; set; }
        public string Imagen { get; set; }
        public string Nombre_tienda { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Tipo_entrega { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Horario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favoritos> favoritos { get; set; }
    }
}
