//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVersionBootstrap4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProduccionTuBajonSVEntities : DbContext
    {
        public ProduccionTuBajonSVEntities()
            : base("name=ProduccionTuBajonSVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<establecimientos> establecimientos { get; set; }
        public virtual DbSet<favoritos> favoritos { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<OPERACIONES> OPERACIONES { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROL_OPERA> ROL_OPERA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
